version: "3.9"
services:
  redis:
    image: 'redis:6.0-alpine'
    volumes:
      - 'redis:/data'

  sidekiq:
    build: .
    volumes:
      - .:/app
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
volumes:
  redis:
